# Nome da aplicacao
spring.application.name=metalurgica

# Configuracoes do Banco de Dados (H2 em arquivo)
spring.datasource.url=jdbc:h2:file:./data/feradb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuracoes JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Para testes altere a linha abaixo para 'create' - para limpar o banco fantasma. Para produção 'update' ou 'validate'
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Console do H2 (Acesse em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Servidor e Encoding
server.port=8080
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Configuracao de Upload
upload.dir=uploads/fera-metalurgica-website
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.sql.init.mode=always

# Atrasa a execucao do data.sql para DEPOIS que o Hibernate criar/atualizar as tabelas
spring.jpa.defer-datasource-initialization=true
